language: java
jdk:
  - oraclejdk8
  - oraclejdk7
test:
  - mvn test -Dmaven.test.skip=true
install:
  - mvn install -Dmaven.test.skip=true
after_success:
  - mvn cobertura:cobertura coveralls:report
